blueprints/acc.py
from flask import Blueprint, request, session, redirect, render_template, url_for
import sqlite3
from blueprints.all_plans import get_names_done

#konta lapa
acc_bp = Blueprint("acc", __name__)

@acc_bp.route("/<username>", methods=["GET","POST"])
def acc(username):
  """Veido konta lapu, izmantojot template acc.html. Lapā var apskatīt lietotāja radītāju tabulu un nodzēst kontu."""
  if "username" not in session:
    return redirect(url_for("login.login"))
  
  in_progress = []
  in_progress_st = []
  not_started_count = 0
  completed_count = 0

  #radītāju tabula
  names_dones = get_names_done(session["username"])
  for name in names_dones:
    done_st = list(map(int, name[1].split(','))) 

    if sum(done_st) == len(done_st):
      completed_count += 1
    elif sum(done_st) == 0:
      not_started_count += 1
    else:
      in_progress.append(name)
      in_progress_st.append((sum(done_st), len(done_st)))

  #konta dzēšana
  if request.method == "POST":
    with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      cur.execute("PRAGMA foreign_keys = ON")
      cur.execute(" DELETE FROM Users WHERE username=? ", (username,))
      conn.commit()
    session.pop("username", None)
    return redirect("landing")
  
  return render_template("acc.html", logged_in=True, name=username, in_progress=in_progress, in_progress_st=in_progress_st, completed_count=completed_count, not_started_count=not_started_count)
  

blueprints/all_plans.py
from flask import Blueprint, request, session, redirect, render_template, url_for
import sqlite3

def get_names_done(username):
  """Atgriež visus lietotāja plānus nosaukumus un statusus."""
  with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      sql = " SELECT name, done FROM Plans WHERE username=?"
      cur.execute(sql, (username,))

      result = cur.fetchall()
  conn.close()
  return result

#visu plānu lapa
visi_bp = Blueprint("visi", __name__)

@visi_bp.route("/visi_plani", methods=["POST", "GET"])
def visi():
  """Veido visu plānu lapu, izmantojot template visi.html. Lapā var apskatīt un piekļūt visiem plāniem, kas ir sadalīti kategorijās."""
  if "username" not in session:
    return redirect(url_for("login.login"))
  
  in_progress = []
  in_progress_st = []
  completed_plans = [] 
  completed_plans_st = []
  not_started = []
  not_started_st = []

  #tabulu veidošana - plāni, kas ir progresā, neuzsākti un uzsākti un progress tājos
  names_dones = get_names_done(session["username"])
  for name in names_dones:
    done_st = list(map(int, name[1].split(','))) 

    if sum(done_st) == len(done_st):
      completed_plans.append(name)
      completed_plans_st.append((sum(done_st), len(done_st)))
    elif sum(done_st) == 0:
      not_started.append(name)
      not_started_st.append((sum(done_st), len(done_st)))
    else:
      in_progress.append(name)
      in_progress_st.append((sum(done_st), len(done_st)))

  return render_template("visi.html", logged_in=True, in_progress=in_progress, not_started=not_started, completed_plans=completed_plans, in_progress_st=in_progress_st, not_started_st=not_started_st, completed_plans_st=completed_plans_st)

blueprints/auth.py
from flask import Blueprint, request, session, redirect, render_template, url_for
import sqlite3
import bcrypt

#login lapa
login_bp = Blueprint("login", __name__)

@login_bp.route("/login", methods=["POST", "GET"])
def login():
  """Veido autorizācijas lapu, izmantojot template login.html"""
  if "username" in session:
    return redirect(url_for("landing"))

  if request.method == "POST":
    #dabūt username un password
    name = request.form["name"]
    password = request.form["password"]

    #atrast username ar password datubāzē
    with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      sql = " SELECT username, password FROM Users WHERE username=?"
      cur.execute(sql, (name,))

      result = cur.fetchone()

    if result is None:
      #tāda lietotāja nav
      return render_template("login.html", error="Lietotājvārds vai parole nav pareizi :(")
    
    st_username, st_password = result

    if isinstance(st_password, str):
      st_password = st_password.encode('utf-8')

    if bcrypt.checkpw(password.encode('utf-8'), st_password):
      #parole ir pareiza
      session["username"] = st_username
      return redirect("/")
    else:
      #parole nav pareiza
      return render_template("login.html", error="Lietotājvārds vai parole nav pareizi :(")

  #ja forma netika iesniegta, radīt logina lapu
  return render_template("login.html")

#registrācijas lapa
register_bp = Blueprint("register", __name__)

@register_bp.route("/register", methods=["POST", "GET"])
def register():
  """Veido reģistrācija lapu, izmantojot template register.html"""

  if "username" in session:
    return redirect(url_for("landing"))
  #ja forma tika iesniegta
  if request.method == "POST":
    #dabūt username un password
    name = request.form["name"]
    password = request.form["password"]
    
    #pārbaudīt, vai datubāzē nav lietotāja ar tādu pašu username
    with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      cur.execute(" SELECT username FROM Users WHERE username=? ",(name,))

      result = cur.fetchall()
      
      #ja tāds lietotājs ir, tad atgriezt reģistrācijas lapu ar lūgumu izmainīt lietotājvārdu vai ielogoties
      if len(result) != 0:
        return render_template("register.html", error="Atvainojiet, šīs lietotājvārds jau ir aizņemts! Lūdzu, pamēģiniet citu, vai ielogojieties! :)")
      else: #ja tāda lietotāja nav, tad reģistrēt jauno lietotāju datubāzē
        hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
        sql = " INSERT INTO Users VALUES (?, ?) "
        cur.execute(sql, (name, hashed))
        conn.commit()
        return render_template("register.html", error="Jūsu konts tika izveidots! Lūdzu, ielogojieties! :)")
  #ja forma netika iesniegta, radīt logina lapu
  return render_template("register.html")

#izlogošanās
logout_bp = Blueprint("logout", __name__)

@logout_bp.route("/logout")
def logout():
  """Izlogo lietotāju no konta"""

  session.pop("username", None)
  return redirect(url_for('landing')) 

blueprints/jauns_plans.py
from flask import Blueprint, request, session, redirect, render_template, url_for
import sqlite3
import google.generativeai as genai
import os
import regex
import datetime

#gemini api iestatījumi
os.environ["API_KEY"] = 'APIkey'
genai.configure(api_key=os.environ["API_KEY"])

model_config = {
  "temperature": 0.7,
  "top_p": 0.8,
  "top_k": 5,
  "max_output_tokens": 4096,
}

instruction = """You are a highly qualified and very precise teacher from Latvia. You create detailed, interesting, diverse and useful study plans for your students, according to the Skola2030 standards. You do it in Latvian. And you always name the steps of your plans (like "Nr. ", "Solis", "Uzdevums", "Resursi")"""

model = genai.GenerativeModel('gemini-1.5-flash-latest', generation_config=model_config, system_instruction=instruction)

def gen_resp(temats, limenis, laiks):
  """Atgriež atbildi, izmantojot Gemini AI API un sarakstīto uzvedni."""
  response = model.generate_content(f"""
Hello! 
I am a student from Latvia and enjoy learning new things, but I struggle with planning and understanding what to study at each point.

Here is some information about me:
- I would like to learn (in Latvian): {temats}
- My level is: {limenis}
- I have this amount of time to study: {laiks}

Please create a detailed, diverse, and helpful study plan for me, following the Skola2030 standard in Latvia.

Response Formatting Rules:
1. Language: Write the entire study plan in Latvian.
2. Plan Structure:
   - First, provide a brief, short, condensed title for the study plan (e.g., “Programming Basics Plan”). Do not write any introduction for the plan. Just the name and then the steps.
   - List each study step in sequence, using "Nr. ..." as the label for each new step.
3. For Each Step:
   - Name each component within the step as follows:
      - Laiks: Specify the exact time required (e.g., “2 hours”) and the exact day for the task (considering the time frame given, without skipping days).
      - Solis: Describe the learning step (e.g., “Study data types”).
      - Uzdevums: Describe an exercise to practice this step.
      - Resursi: List recommended resources (e.g., YouTube videos, websites, or documents). Ensure the resources are functional, accurate, and suitable for the topic. Provide no more than 2-3 resources per step, with a brief description of each.

4. Additional Requirements:
   - Ensure all steps are covered in the given timeframe, including every day within the period specified.
   - Avoid skipping any days.
   - Use the specific format and names for each component in the steps (Laiks, Solis, Uzdevums, Resursi).
""")

  plans = response.text.replace("*", " ").replace("#", "").replace("|", "").replace("\n","").replace("[", " ").replace("]", " ")
  nosaukums = plans
  nosaukums = regex.sub(r'\d+\. diena', '', nosaukums.split("Nr")[0].strip()).strip()
  nosaukums = nosaukums + "; " + session["username"]
  return [plans,nosaukums]

def formating(plans):
  """Atgriež pārformatēto Gemini atbildi divdimensiālā masīvā."""

  #sadalīt katru plāna daļu, tās sakās ar "Nr."
  solu_saraksts = regex.split(r"(?=Nr\.\s*\d+)", plans, flags=regex.DOTALL)

  #šablons, pēc kurā dalīt plānu uz daļām
  pattern = r"(Nr\.\s*\d+|Laiks:|Solis:|Uzdevums:|Resursi:)(.*?)(?=Nr\.\s*\d+|Laiks:|Solis:|Uzdevums:|Resursi:|$)"

  viss_plans = []
  #apstrādāt katru soli atsevišķi
  for solis in solu_saraksts:
    if solis.strip():
      matches = regex.findall(pattern, solis, regex.DOTALL)
      elements = [f"{match[0].strip()} {match[1].strip()}" for match in matches]
      viss_plans.append(elements)

  #noņemt iespējamus kļūdaimus sadalījumus
  correct_plan = []
  for plan in viss_plans:
    if plan == []:
      continue
    plan2 = [regex.sub(r'\d+\. diena', '', item).strip() for item in plan]
    correct_plan.append(plan2)

  result = []
  current = []  
    
  for item in correct_plan:
    #ja elements ir list, kas sastāv no 1 elementa 
    if isinstance(item, list) and len(item) == 1:
      #pievienot iepriekšējam elementam
      if current:
        current[-1] += " " + item[0]
    else:
      if current:
        result.append(current) 
      current = item  

  #pievienot finālāi masīva versijai
  if current:
    result.append(current)

  keywords = ["Nr.", "Laiks", "Solis", "Uzdevums", "Resursi"]

  def format_text(item):
    """Pārveido plāna soļus, lai būtu iespējams izmainīt atslēgvārdu stilu."""
    for keyword in keywords:
      item = item.replace(keyword, f"<span>{keyword}</span>")
    return item
  
  last_result = []
  
  for i in result:
    last_result.append([format_text(item) for item in i])

  return last_result

def compare_strings(str1, str2):
    """Salīdzina 2 tekstus, neņēmot vērā punktuāciju un citus simbolus."""

    #noņemt visus simbolus izņēmot burtus un ciparus
    cleaned_str1 = regex.sub(r'[^A-Za-z0-9]', '', str1).lower()
    cleaned_str2 = regex.sub(r'[^A-Za-z0-9]', '', str2).lower()
  
    return cleaned_str1 == cleaned_str2
  
jauns_bp = Blueprint("jauns", __name__)

@jauns_bp.route("/jauns", methods=["POST", "GET"])
def jauns():
  correct_plan = []
  nosaukums = ""
  tosave = {"plans": "", "nosaukums": "", "done_st": ""}
  if "username" not in session:
    return redirect(url_for("login.login"))
  if request.method == "POST":
    #dabūt ievadus
    temats = request.form["temats"]
    nedelas = request.form["nedelas"]
    stundas = request.form["stundas"]
    limenis = request.form["zinlim"]

    laiks = f"{str(nedelas)} nedēļas pa {str(stundas)} stundām dienā."
    
    #saglabāt request
    with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      sql = " INSERT INTO Requests (temats, laiks, limenis, username, time) VALUES (?, ?, ?, ?, ?)"
      cur.execute(sql, (temats, laiks, limenis, session["username"], str(datetime.datetime.now())))

    #saglabāt pēdējos datus sessijā
    session["temats"] = temats
    session["laiks"] = laiks
    session["limenis"] = limenis

    #pārbaudīt, vai lietotājam jau nav tāda plāna
    with sqlite3.connect("users.db") as conn:
      cur = conn.cursor()
      sql = " SELECT name FROM Plans WHERE username=? "
      cur.execute(sql, (session["username"],))

      result = cur.fetchall()

    planame = temats + "; " + session["username"]
    for i in result:
      if compare_strings(i[0], planame):
        return render_template("jauns.html", logged_in=True, plans=["",""], nosaukums="Jūms jau ir plāns par šo tematu. Lūdzu, izvelieties citu!", tosave=tosave)

    if limenis == "uzsacejs":
      limenis = "a total beginner at this subject"
    elif limenis == "videjais":
      limenis = "intermediate at this subject"
    else:
      limenis = "a professional who wants to understand the subject deeply"
    
    #plāna ģenerēšana
    cycles = 0
    while True:
      resp = gen_resp(temats,laiks,limenis)
      plans = resp[0]
      nosaukums = resp[1]
      cycles += 1
      print(nosaukums)
      if cycles >= 5: #ja ģenerācija nenostrādāja pareizi 5 reizes
        return render_template("jauns.html", logged_in=True, plans=["",""], nosaukums="Kļūda plāna ģenerēšanā. Lūdzu, izmainiet savas prasības vai atjaunojiet lapu un pamēģiniet vēlreiz.", tosave=tosave)
      if len(nosaukums) <= 120: #ja formātējums salūza, pārģenerēt
        break
    
    #plāna formatējums
    correct_plan = formating(plans)

    #progresa statusi
    done_st = ["0" for _ in range(len(correct_plan))]
    done_st = ",".join(done_st)

    nosaukums = temats + "; " + session["username"]

    tosave = {"plans":plans, "nosaukums":nosaukums, "done_st": done_st}
        
  return render_template("jauns.html", logged_in=True, plans=correct_plan, nosaukums=nosaukums, tosave=tosave)

#plāna saglabāšana
save_bp = Blueprint("save", __name__)
@save_bp.route("/savereturn", methods=['POST'])
def save():
  """Saglabā plānu datubāzē."""
  if "username" not in session:
    return redirect(url_for("login.login"))
  
  plans = request.form.get("plans")
  nosaukums = request.form.get("nosaukums")
  done_st = request.form.get("done_st")

  with sqlite3.connect("users.db") as conn:
    cur = conn.cursor()
    cur.execute("""
      INSERT INTO Plans (username, plan, name, done) 
      VALUES (?, ?, ?, ?)
    """, (session["username"], plans, nosaukums, done_st))
    conn.commit()

  return redirect("/visi_plani")

#reģenerēšana
regenerate_bp = Blueprint("regenerate", __name__)
@regenerate_bp.route("/regenerate", methods=['POST'])
def regenerate():
  """Reģenerē plānu ar tiem pašiem pieprasījumiem."""
  correct_plan = []
  tosave = {"plans": "", "nosaukums": "", "done_st": ""}
  if "username" not in session:
    return redirect(url_for("login.login"))
  
  #dabūt lietotāja pēdējo pieprasījumu
  temats = session.get("temats")
  laiks = session.get("laiks")
  limenis = session.get("limenis")

  if not temats or not laiks or not limenis:
    return redirect(url_for("jauns")) 

  #ģenerēt plānu
  cycles = 0
  while True:
    resp = gen_resp(temats, laiks, limenis)
    plans = resp[0]
    nosaukums = resp[1]
    cycles += 1
    if cycles >= 5:  
      return render_template("jauns.html", logged_in=True, plans=["",""], nosaukums="Kļūda plāna ģenerēšanā. Lūdzu, izmainiet savas prasības vai atjaunojiet lapu un pamēģiniet vēlreiz.", tosave=tosave)
    if len(nosaukums) <= 120:
      break

  #plāna formatēšana
  correct_plan = formating(plans)
  done_st = ",".join(["0" for _ in range(len(correct_plan))])
  nosaukums = temats + "; " + session["username"]

  tosave = {"plans": plans, "nosaukums": nosaukums, "done_st": done_st}

  return render_template("jauns.html", logged_in=True, plans=correct_plan, nosaukums=nosaukums, tosave=tosave)

templates/acc.html
{% extends  "base.html" %}
{% block title %} {{ name }} {% endblock %}

{% block content %}
  <div class="account">
    <h1>{{ name }}</h1>
    <h3>Plāni, kas ir progresā</h3>
    <table>
      <tr>
        <th>Plāna nosaukums</th>
        <th>Progress</th>
      </tr>
      {% for i in range(in_progress|length) %}
      <tr>
        <td><a href="{{ url_for('single.single', nosaukums=in_progress[i][0]) }}">{{in_progress[i][0]}}</a></td>
        <td><progress value="{{ in_progress_st[i][0] }}" max="{{ in_progress_st[i][1] }}"></progress></td>
      </tr>
      {% endfor %}
    </table> 
    <h3> Jūs pabeidzāt {{completed_count}} plānus, un Jums ir {{not_started_count}} neuzsākti plani! </h3>
    <hr> <br>
    <form method="POST">
      <button type="submit">Nodzēst kontu</button>
    </form>
    <p>*Šī darbība ir neatgriezeniskā. Visi uzģenerēti plāni arī tiks nodzēsti.</p>
  </div>
  
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
</head>
<body>
  <nav>
    <div class="nav-container">
      <ol>
        <li class="header"><a href="{{ url_for('landing') }}">Pašmācību plānu ģenerātors</a></li>
        <div class="pages">
        {% if not logged_in %}
          <li class="page"><a href="{{ url_for('login.login') }}">Autorizēties</a></li>
          <li class="page"><a href="{{ url_for('register.register') }}">Reģistrēties</a></li>
        {% else %}
          <li class="page"><a href="{{ url_for('jauns.jauns') }}">Jauns mācību plāns</a></li>
          <li class="page"><a href="{{ url_for('visi.visi') }}">Visi mācību plāni</a></li>
          <li class="page"><a href="{{ url_for('acc.acc', username=session['username']) }}">{{ session["username"] }}</a></li>
          <li class="page"><a href="{{ url_for('logout.logout') }}">Izlogoties</a></li>
          {% endif %}
        </div>  
      </ol>
    </div>
  </nav>

  <div class="content">
    {% block content %}{% endblock %}
  </div>
  
</body>
</html>

templates/jauns.html
{% extends 'base.html' %}
{% block title %} Jauna plāna ģenerēšana {% endblock %}

{% block content %}
  <div id="loader" class="loader">
    <div class="spinner"></div>
    <p>Plāns ģenerējas...</p>
  </div>

  <div class="jauns">
    <h2>Uzģenerējiet personalizētu mācību plānu pašmācībām jebkuram priekšmetam un tematam!</h2>
    <form id="generate-form" action="/jauns" method="POST">
      <br>
      <label for="temats"><span>Mācību plāna temats</span> - pēc iespējas precīzāk aprakstiet, par ko Jums ir jāmācās, piemēram,<br> "Jaukti salikti teikumi angļu valodā, 12. klasei."</label><br>
      <input type="text" name="temats" placeholder="Par ko izveidot mācību plānu?" required>
      <br>
      <br>
      <label for="nedelas"><span>Laika apjoms</span> - cik daudz Jums ir laika, piemēram, 2 nedēļas pa 2 stundām dienā.</label>
      <div class="laiks">
        <input type="number" name="nedelas" id="nedelas" max="5" min="1" required> <p> nedēļas pa </p>
        <input type="number" name="stundas" id="stundas" max="9" min="1" required> <p> stundām dienā.</p>
      </div>
      <br>
      <br>
      <label for="zinlim">Kāds ir Jūsu <span>zināšanu līmenis?</span></label><br>
        <select name="zinlim" id="zinlim">
          <option value="uzsacejs">Uzsācējs (vispār neko nezinu par tematu)</option>
          <option value="videjais">Vidējais (kaut ko zinu un saprotu, bet ne visu)</option>
          <option value="profesionals">Profesionāls (zinu un saprotu tematu, gribu padziļināt izpratni un pārliecināties zināšanās)</option>
        </select>
      <input type="submit" value="Uzģenerēt!" class="submit">
    </form>
    <br>
    {% if plans != [] %}
      {% if nosaukums != "Kļūda plāna ģenerēšanā. Lūdzu, izmainiet savas prasības vai atjaunojiet lapu un pamēģiniet vēlreiz." and nosaukums != "Jūms jau ir plāns par šo tematu. Lūdzu, izvelieties citu!" %}
        <h2 id="generated-plan">{{nosaukums}}</h2>
        {% for solis in plans %}
        <ul>
          <div class="solis">
            {% for detail in solis %}
              <li>{{ detail|safe }}</li>
            {% endfor %}
          </div>
        </ul>
          {% endfor %}
          
        <div class="buttons">
          <form action="/savereturn" method="POST">
            <input type="hidden" name="plans" value="{{ tosave['plans'] }}">
            <input type="hidden" name="nosaukums" value="{{ tosave['nosaukums'] }}">
            <input type="hidden" name="done_st" value="{{ tosave['done_st'] }}">
            <button type="submit">Saglabāt</button>
          </form>
          <form id="regenerate-form" action="/regenerate" method="POST">
            <button type="submit">Pārģenerēt</button>
          </form>
        </div>
      {% else %}
        <h2 id="generated-plan">{{nosaukums}}</h2>
      {% endif %}
    {% endif %}
  </div>
  <script>
    window.onload = function() {
      if (document.getElementById('generated-plan')) {
        document.getElementById('generated-plan').scrollIntoView({ behavior: 'smooth' });
      }
    };

    document.getElementById('generate-form').addEventListener('submit', function () {
      document.getElementById('loader').style.display = 'flex';
    });

    document.getElementById('regenerate-form').addEventListener('submit', function () {
      document.getElementById('loader').style.display = 'flex';
    });

  </script>
{% endblock %}

templates/landing.html
{% extends 'base.html' %}

{% block title %}Pašmācību plānu ģenerātors{% endblock %}
{% block content %}
  <div class="landhi">
    {% if "username" in session %}
      <h3>Laipni lūgti, {{ session["username"] }}</h3>
    {% else %}
      <h3>Laipni lūgti! Lūdzu, <a href="{{ url_for('login.login') }}">ielogojieties</a> vai <a href="{{ url_for('register.register') }}">reģistrējies</a>, lai izmantotu vietnes funkcijas.</h3>
    {% endif %}
  </div>
    <div class="land">
      <div class="sections">
        <h2>Jauno plānu ģenerēšana!</h2>
        <p> Izveidojiet Sev piemēroto mācību plānu jebkuram mācību priekšmetam un tematam, norādot tikai pašu tematu, pieejamo laiku un zināšanu līmeni!</p>
        <p> Glabājiet Savus plānus, lai izmantotu tos ērtā veidā!</p>
        <a class="abutton" href="{{ url_for('jauns.jauns') }}">Izveidot jaunu plānu</a>
      </div>
      <div class="sections">
        <h2>Esošo plānu pārskats!</h2>
        <p> Apskatiet Savus iepriekš izveidotus plānus un to izpildes statusus, sadalītus kategorijās pēc Jūsu progresa!</p>
        <p> Izvēlieties plānu, kuru vēlieties pildīt vai apskatīt precīzi, un turpiniet mācīties! </p>
        <a class="abutton" href="{{ url_for('visi.visi') }}">Apskatīt plānus</a>
      </div>
      <div class="sections">
        <h2>Sekošana progresam!</h2>
        <p> Azīmējiet, kurus soļus no plāna jau esat izpildījis/usi, un progresa līnija paradīs Jūsu sasniegumus pašmācībās! </p>
        <p> Apskatot visus plānus, redzēsiet progresu visos priekšmētos/tematos, kurus mēģinājāt pašvadīti apgūt!</p>
        <a class="abutton" href="{{ url_for('visi.visi') }}">Apskatīt plānus</a>
      </div>
    </div>
    
{% endblock %}



templates/login.html
{% extends 'base.html' %}

{% block title %}Ielogošanās{% endblock %}
{% block content %}
  <div class="login">
    <h1>Autorizējies!</h1>
    <p>{{ error }}</p>
    <form method="POST">
      <br>
      <input type="text" name="name" placeholder="Lietotājvārds" required>
      <br>
      <br>
      <input type="password" name="password" placeholder="Parole" required>
      <br>
      <br>
      <input type="submit" value="Iesniegt" class="submit">
    </form>
    <br>
    <h3>Vēl nav konta? <a href="{{ url_for('register.register') }}">Reģistrējies!</a></h3>
  </div>
{% endblock %}

templates/plan.html
{% extends  "base.html" %}
{% block title %} {{ username }} plāns {% endblock %}

{% block content %}
  <div class="single">
    <a href="{{ url_for('visi.visi') }}">Atgriezties pie visiem plāniem</a>
    <h1>{{ nosaukums }}</h1>
    <progress value="{{ completed }}" max="{{ total }}"></progress>
    <p>Jūs izpildījāt {{ perc }}% no plāna!</p>
    <ul>
      {% for i in range(plans|length) %}
        <li class="butnstep {% if statuses[i] == 1 %} completed {% else %} not-completed {% endif %}">
          <form method="POST" class="btn">
            <button 
              type="submit" 
              name="step_{{ i }}" 
              value="{{ statuses[i] }}" 
              class="{% if statuses[i] == 1 %} btn-completed {% else %} btn-not-completed {% endif %}">
            </button>
          </form>
          <ul>
            <div class="solis">
              {% for detail in plans[i] %}
                <li>{{ detail|safe }}</li>
              {% endfor %}
            </div>
          </ul>
        </li>
      {% endfor %}
    </ul>
    <center>
    <form action="{{ url_for('delete.delete', nosaukums=nosaukums) }}" method="POST">
      <button type="submit" class="deletebtn">Nodzēst Plānu</button>
    </form>
    </center>
  </div>
  
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}Reģistrācija{% endblock %}
{% block content %}
  <div class="login">
    <h1>Reģistrējies</h1>
    <p>{{ error }}</p>
    <form method="POST">
      <br>
      <input type="text" name="name" placeholder="Lietotājvārds" required>
      <br>
      <br>
      <input type="password" name="password" placeholder="Parole" pattern=".{8,}" title="Parolē ir jābūt vismaz 8 simboliem" required>
      <br>
      <br>
      <input type="submit" value="Iesniegt" class="submit">
    </form>
    <br>
    <h3>Jau ir konts? <a href="{{ url_for('login.login') }}">Autorizējies!</a></h3>
  </div>

{% endblock %}

templates/visi.html
{% extends 'base.html' %}
{% block title %} Visi plāni {% endblock %}

{% block content %}
  <div class="all">
    <h2>Plāni, kas ir progresā</h2>
    <table>
      <tr>
        <th>Plāna nosaukums</th>
        <th>Progress</th>
      </tr>
      {% for i in range(in_progress|length) %}
      <tr>
        <td><a href="{{ url_for('single.single', nosaukums=in_progress[i][0]) }}">{{in_progress[i][0]}}</a></td>
        <td><progress value="{{ in_progress_st[i][0] }}" max="{{ in_progress_st[i][1] }}"></progress></td>
      </tr>
      {% endfor %}
    </table> 
    <h2>Neuzsāktie plāni</h2>
    <table>
      <tr>
        <th>Plāna nosaukums</th>
        <th>Progress</th>
      </tr>
      {% for i in range(not_started|length) %}
      <tr>
        <td><a href="{{ url_for('single.single', nosaukums=not_started[i][0]) }}">{{not_started[i][0]}}</a></td>
        <td><progress value="{{ not_started_st[i][0] }}" max="{{ not_started_st[i][1] }}"></progress></td>
      </tr>
      {% endfor %}
    </table> 
    <h2>Pabeigtie plāni</h2>
    <table>
      <tr>
        <th>Plāna nosaukums</th>
        <th>Progress</th>
      </tr>
      {% for i in range(completed_plans|length) %}
      <tr>
        <td><a href="{{ url_for('single.single', nosaukums=completed_plans[i][0]) }}">{{completed_plans[i][0]}}</a></td>
        <td><progress value="{{ completed_plans_st[i][0] }}" max="{{ completed_plans_st[i][1] }}"></progress></td>
      </tr>
      {% endfor %}
    </table> 
    <p>{{ done }}</p>
  </div>
{% endblock %}